### PR TITLE
Node file system-based save & load

### PR DESCRIPTION
**Pull request by caisq**
FEATURE: Add support for `file://` URLs for saving and loading `tf.Model`s in tfjs-node.

Towards: https://github.com/tensorflow/tfjs/issues/343

This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/100)

### CODE REVIEW

**Comment by nkreeger** [comment]
This is looking great - I took an early pass while I had some cycles this morning! Ping me if I said something that doesn't make sense.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/io/file_system.ts, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvhi-v5AFgKJeio_Lw:-LDvhi-v5AFgKJeio_Lx:bn70rk0) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L42)):*
> ```XML
>   async save(modelArtifacts: tfc.io.ModelArtifacts):
>       Promise<tfc.io.SaveResult> {
>     if (Array.isArray(this.path)) {
> ```

This is coming soon support? Is there an issue to track this?

---

*[src/io/file_system.ts, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvhqUQ9WXrdQJFvl0B:-LDvhqUQ9WXrdQJFvl0C:b68g3ew) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L48)):*
> ```XML
>     this.createOrVerifyDirectory();
> 
>     if (modelArtifacts.modelTopology instanceof ArrayBuffer) {
> ```

Ditto here about an issue to track this.

---

*[src/io/file_system.ts, line 65 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvgmHQCyKdbAUcP0Jg:-LDvgmHQCyKdbAUcP0Jh:b-498dxw) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L65)):*
> ```XML
>       fs.writeFileSync(modelJSONPath, JSON.stringify(modelJSON));
> 
>       fs.writeFileSync(
> ```

It's best practice to not use the sync functions in Node.js

However, there is a great API to make this easy: https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original

```js
const writeFile = util.promisify(fs.writeFile);
...
await writeFile(modelJSONPath, JSON.stringify(modelJSON);
```

Same throughout here.

---

*[src/io/file_system.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvhKIgCOQwfLe0r17C:-LDvhKIh8BeeGey8USGR:b-mbhv49) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L69)):*
> ```XML
> 
>       return {
>         // tslint:disable-next-line:no-any
> ```

Is there not a type in core for this?

---

*[src/io/file_system.ts, line 80 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvi-Tw3Yenx3GS3W4n:-LDvi-Tw3Yenx3GS3W4o:bozwrzr) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L80)):*
> ```XML
>     }
> 
>     if (!fs.existsSync(this.path)) {
> ```

Use `util.promisify()` here too - same throughout sync functions here.

---

*[src/io/file_system.ts, line 98 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDviEaoC82Uevg2IuBp:-LDviEaoC82Uevg2IuBq:b-kp7hld) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L98)):*
> ```XML
>         for (const group of modelJSON.weightsManifest) {
>           group.paths.forEach((path: string) => {
>             console.log('pushing data from path = ' + path);  // DEBUG
> ```

Cleanup.

---

*[src/io/file_system.ts, line 109 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDviIAQCFBAf5pt0NNv:-LDviIAQCFBAf5pt0NNw:bunfp3u) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L109)):*
> ```XML
>       return modelArtifacts;
>     } else {
>       throw new Error(
> ```

Issue.

---

*[src/io/file_system.ts, line 116 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDviJZc2zetniOcIPVI:-LDviJZc2zetniOcIPVJ:bv6rhj3) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L116)):*
> ```XML
> 
>   /**
>    * Create a directory at `this.path` or verify that the directory exists.
> ```

Curious - are we keeping google style here by writing these in 3rd person singular? `"Creates..."`

---

*[src/io/file_system.ts, line 134 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDviY165frN42n-oRhr:-LDviY165frN42n-oRhs:bwjnjoc) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L134)):*
> ```XML
> 
> export const nodeFileSystemRouter = (url: string) => {
>   if (tfc.ENV.get('IS_BROWSER')) {
> ```

Is this an actual possibility? I feel like we might need to handle this elsewhere because I can see it becoming an issue down the road in other parts of this package.

---

*[src/io/file_system.ts, line 140 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvigFl-xDd_mxEWZL5:-LDvigFl-xDd_mxEWZL6:b-9yb8xp) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L140)):*
> ```XML
>       return new NodeFileSystem(url.slice(NodeFileSystem.URL_SCHEME.length));
>     } else {
>       return null;
> ```

Might be worthy of a console.log() here. Do we have docs for users that need to write their own plugin for this?

---

*[src/io/file_system.ts, line 147 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvimEY9RfOM60q4plf:-LDvimEZ-eg8jXfbq00u:bbq6t56) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L147)):*
> ```XML
> tfc.io.registerLoadRouter(nodeFileSystemRouter);
> 
> // TODO(cais): Deduplicate with tfjs-core once the dependency version is
> ```

We just updated :-)

---

*[src/io/file_system_test.ts, line 162 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvitT09OrNlRlXrtrV:-LDvitT09OrNlRlXrtrW:b-vighbv) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system_test.ts#L162)):*
> ```XML
> 
>   it('save-load round trip: two weight files', done => {
>     console.log('=============== BEGIN ===============');  // DEBUG
> ```

Cleanup here too

---

*[src/io/file_system_test.ts, line 194 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvivHxALFfs5b0gOkH:-LDvivHxALFfs5b0gOkI:b8ne46m) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system_test.ts#L194)):*
> ```XML
>     // Write the two binary weights files.
>     console.log('----------------------------------------');   // DEBUG
>     console.log(new Float32Array([-1.1, -3.3, -3.3]).buffer);  // DEBUG
> ```

Looks like this block has some good ol' printf() debugging :-)

---

*[src/io/io_utils.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvjKi8EBYy4l-1E7tP:-LDvjKi8EBYy4l-1E7tQ:b-a7fa2e) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/io_utils.ts#L31)):*
> ```XML
> 
> /**
>  * Convert a Buffer or an Array of Buffers to an ArrayBuffer.
> ```

Ditto in this file about the 3rd person singular usage.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-:-LDvjbIWA_VXLZPxslY_:b-24guog)*

**Comment by caisq** [comment]
Thanks for the review, Nick!

---

Review status: 0 of 7 files reviewed at latest revision, 14 unresolved discussions.

---

*[src/io/file_system.ts, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvhi-v5AFgKJeio_Lw:-LDw1sIq2dse6VPKf4A3:b9lman1) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L42)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

This is coming soon support? Is there an issue to track this?
</blockquote></details>

The same issue tracks this for now: https://github.com/tensorflow/tfjs/issues/343

I added a doc string to the constructor to explain when an Array of path strings should be used.

---

*[src/io/file_system.ts, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvhqUQ9WXrdQJFvl0B:-LDw28c68mhqhkIAeN1q:bzemkfl) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L48)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Ditto here about an issue to track this.
</blockquote></details>

Ditto the reply above.

---

*[src/io/file_system.ts, line 65 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvgmHQCyKdbAUcP0Jg:-LDw5UzzDbAfClxy267P:b59t3ep) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L65)):*
> promisify

Good point! Thanks. Using promisify throughout the added files.

---

*[src/io/file_system.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvhKIgCOQwfLe0r17C:-LDw2PMuEhtL-zZtmIY8:b8sy647) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L69)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Is there not a type in core for this?
</blockquote></details>

Unfortunately we can't use the explicit tfc.io.ModelArtifactsInfo type yet. Added a TODO item here.

---

*[src/io/file_system.ts, line 98 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDviEaoC82Uevg2IuBp:-LDw3E-N9O2qNXvXkYqD:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L98)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Cleanup.
</blockquote></details>

Done.

---

*[src/io/file_system.ts, line 116 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDviJZc2zetniOcIPVI:-LDw3NRt6mIrUI31quqF:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L116)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Curious - are we keeping google style here by writing these in 3rd person singular? `"Creates..."`
</blockquote></details>

Done.

---

*[src/io/file_system.ts, line 134 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDviY165frN42n-oRhr:-LDw3T7v7SE9BvC6-YXo:bwlc1b6) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L134)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Is this an actual possibility? I feel like we might need to handle this elsewhere because I can see it becoming an issue down the road in other parts of this package.
</blockquote></details>

Good point. I don't see this as a reasonable possibility here, at least not currently. Removed this check. We can explore more robust checks for browser later.

---

*[src/io/file_system.ts, line 140 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvigFl-xDd_mxEWZL5:-LDw3iIQ5yse3BVfU4xK:b51l56b) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L140)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Might be worthy of a console.log() here. Do we have docs for users that need to write their own plugin for this?
</blockquote></details>

Doc is not available yet.

---

*[src/io/file_system.ts, line 147 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvimEY9RfOM60q4plf:-LDw3nLr54v_BJr39lCY:b4i4xx7) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L147)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

We just updated :-)
</blockquote></details>

It turns out that we can't use that exported function. Sigh...

The function uses `Blob`, which is not available in node. It looks like that the way to calculate the byte size of a potentially non-ASCII string is inevitably different between browser and node.js. In node.js, we just use Buffer.byteLength, which is not available in browser. So we should keep this function. Also, I moved this function to io_utils.ts.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-:-LDwBBxY1aa6bTQhseHe:bljcmyi)*

**Comment by nkreeger** [comment]
:lgtm_strong: Couple of small comments - nothing blocking. Thanks for the hard work on this! 

---

Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/io/file_system.ts, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvhi-v5AFgKJeio_Lw:-LDwfB1cAb9x0dsLE1ku:bj69ota) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L42)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

The same issue tracks this for now: https://github.com/tensorflow/tfjs/issues/343

I added a doc string to the constructor to explain when an Array of path strings should be used.
</blockquote></details>

OK cool - do you think it makes sense to add a link here to that issue?

---

*[src/io/file_system.ts, line 36 at r2](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDwexaRAO5ufYmD6Krg:-LDwexaRAO5ufYmD6Krh:b-z60s6f) ([raw file](https://github.com/tensorflow/tfjs-node/blob/844d052bdefde73c2441313e4121b5da5bcce6ba/src/io/file_system.ts#L36)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>    * @param path A single path or an Array of paths.
>    *   For saving: expects a single path pointing to an existing or nonexistent
>    *     directory. If the directory does not exist, it will be
>    *     created. For loading:
>    *     - If the model has JSON topology (e.g., `tf.Model`), a single path
>    *       pointing to the JSON file (usually named `model.json`) is expected.
>    *       The JSON file is expected to contain `modelTopology` and/or
>    *       `weightsManifest`. If `weightManifest` exists, the values of the
>    *       weights will be loaded from relative paths (relative to the directory
>    *       of `model.json`) as contained in `weightManifest`.
>    *     - If the model has binary (protocol buffer GraphDef) topology,
>    *       an Array of two paths is expected: the first path should point to the
>    *       .pb file and the second path should point to the weight manifest
> ```
</details>


Might be a good option to add this to the mnist example after we get a package published with these changes. We can document basic Node.js model saving there as a good canonical case.

---

*[src/io/file_system_test.ts, line 85 at r2](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDwfoc85YvL7xbsyMXQ:-LDwfoc85YvL7xbsyMXR:bvtv19u) ([raw file](https://github.com/tensorflow/tfjs-node/blob/844d052bdefde73c2441313e4121b5da5bcce6ba/src/io/file_system_test.ts#L85)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     //   if (err) {
>     //     done.fail('Failed to create temporary directory.');
>     //   } else {
>     //     testDir = path;
>     //     done();
>     //   }
> ```
</details>

 Looks like a little cleanup here?

---

*[src/io/io_utils.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvjKi8EBYy4l-1E7tP:-LDwg3cbDLTf3rLHFhye:bx6eggn) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/io_utils.ts#L31)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Ditto in this file about the 3rd person singular usage.
</blockquote></details>

Looks like this might have been lost in the Reviewable - what do you think about 3rd person singular here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-:-LDwgK6F8YbeTMiAhA57:bhwk5zf)*

**Comment by caisq** [comment]
Review status: 0 of 7 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[src/io/file_system.ts, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvhi-v5AFgKJeio_Lw:-LDwjhuRAWnicMZNMZ-Z:b-r7hsvp) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L42)):*
> link

Done.

---

*[src/io/file_system.ts, line 80 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvi-Tw3Yenx3GS3W4n:-LDwjDsr6E7XRLliCgx4:bbarh5g) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/file_system.ts#L80)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Use `util.promisify()` here too - same throughout sync functions here.
</blockquote></details>

Done. Using promisify throughout file_system.ts and file_system_test.ts

---

*[src/io/file_system.ts, line 36 at r2](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDwexaRAO5ufYmD6Krg:-LDwj1Pp2IpIvUxaNtx-:b-pbdqz3) ([raw file](https://github.com/tensorflow/tfjs-node/blob/844d052bdefde73c2441313e4121b5da5bcce6ba/src/io/file_system.ts#L36)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

> ```
>    * @param path A single path or an Array of paths.
>    *   For saving: expects a single path pointing to an existing or nonexistent
>    *     directory. If the directory does not exist, it will be
>    *     created. For loading:
>    *     - If the model has JSON topology (e.g., `tf.Model`), a single path
>    *       pointing to the JSON file (usually named `model.json`) is expected.
>    *       The JSON file is expected to contain `modelTopology` and/or
>    *       `weightsManifest`. If `weightManifest` exists, the values of the
>    *       weights will be loaded from relative paths (relative to the directory
>    *       of `model.json`) as contained in `weightManifest`.
>    *     - If the model has binary (protocol buffer GraphDef) topology,
>    *       an Array of two paths is expected: the first path should point to the
>    *       .pb file and the second path should point to the weight manifest
> ```

Might be a good option to add this to the mnist example after we get a package published with these changes. We can document basic Node.js model saving there as a good canonical case.
</blockquote></details>

Agreed.

---

*[src/io/file_system_test.ts, line 85 at r2](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDwfoc85YvL7xbsyMXQ:-LDwin2G5vS14scLebR-:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-node/blob/844d052bdefde73c2441313e4121b5da5bcce6ba/src/io/file_system_test.ts#L85)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

> ```
>     //   if (err) {
>     //     done.fail('Failed to create temporary directory.');
>     //   } else {
>     //     testDir = path;
>     //     done();
>     //   }
> ```
 Looks like a little cleanup here?
</blockquote></details>

Done.

---

*[src/io/io_utils.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/100#-LDvjKi8EBYy4l-1E7tP:-LDwiuvjAukRxBmNHe6Z:bet74a8) ([raw file](https://github.com/tensorflow/tfjs-node/blob/1de3316750391ef71774a6d297a15830685818ef/src/io/io_utils.ts#L31)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Looks like this might have been lost in the Reviewable - what do you think about 3rd person singular here?
</blockquote></details>

The doc string is using 3rd person singular now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/100)*

**Pull request merged**
