### PR TITLE
Fix problem that not uses proxy

### PR DESCRIPTION
**Pull request by haoyunfeix**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/244)

### CODE REVIEW

**Comment by haoyunfeix** [comment]
I signed it! for CLA

**Comment by haoyunfeix** [comment]
@nkreeger PTAL

**Comment by kazuhitoyokoi** [comment]
@haoyunfeix I encountered the proxy problem and just wrote the same code change. I'm looking forward to using the fixed version of tfjs-node module.

**Comment by zuhito** [comment]
I'd really like to the fixed module in my hands-on. Could you publish it on npm repository? 🙏 🙏 🙏

**Pull request merged**
