### PR TITLE
[WIP] Add integration_tests/benchmarks

### PR DESCRIPTION
**Pull request by caisq**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/225)

### CODE REVIEW

**Comment by nkreeger** [comment]
Trying to run this on MacOS: 

```sh
> ./run-benchmarks.sh 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting keras==2.2.4 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl
Collecting tensorflow-gpu==1.12.0 (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement tensorflow-gpu==1.12.0 (from -r requirements.txt (line 2)) (from versions: 0.12.0rc1, 0.12.0, 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0)
No matching distribution found for tensorflow-gpu==1.12.0 (from -r requirements.txt (line 2))
```

**Comment by caisq** [comment]
@nkreeger There is no tensorflow-gpu on Mac. Try changing tensorflow-gpu to tensorflow in requirements.txt.

**Comment by nkreeger** [comment]
Gets further but still fails:

```sh
tensorflowjs 0.8.0 has requirement h5py==2.8.0, but you'll have h5py 2.9.0 which is incompatible.
tensorflowjs 0.8.0 has requirement keras==2.2.2, but you'll have keras 2.2.4 which is incompatible.
tensorflowjs 0.8.0 has requirement numpy==1.15.1, but you'll have numpy 1.16.2 which is incompatible.
tensorflowjs 0.8.0 has requirement six==1.11.0, but you'll have six 1.12.0 which is incompatible.
tensorflowjs 0.8.0 has requirement tensorflow==1.12.0, but you'll have tensorflow 1.13.1 which is incompatible.
tensorflowjs 0.8.0 has requirement tensorflow-hub==0.1.1, but you'll have tensorflow-hub 0.3.0 which is incompatible.
Installing collected packages: pyyaml, scipy, keras, tensorflow-estimator, tensorboard, tensorflow, tensorflow-hub, tensorflowjs
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/PyYAML-5.1.dist-info'
Consider using the `--user` option or check the permissions.
```

I tried a newer version of tensorflowjs but still having trouble. Also tfjs-node 1.0.2 is TF 1.13.1.

**Comment by caisq** [comment]
@nkreeger Sorry, I haven't polished this PR to a state for wide usage yet. Please create a virtualenv and run the scripts inside that.

```sh
virtualenv ~/my_venv
source ~/my_venv/bin/activate
```

@dsmilkov has run that successfully.

**Comment by caisq** [comment]
(The current title of this PR indicates it's WIP)

**Comment by caisq** [comment]
Context: what this PR aimed to achieve has been achieved in https://github.com/tensorflow/tfjs/tree/master/tfjs/integration_tests

**Pull request closed without merging**
