### PR TITLE
Rename module tfjs-node => @tensorflow/tfjs-node

### PR DESCRIPTION
**Pull request by ry**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/78)

### CODE REVIEW

**Comment by nkreeger** [comment]
:lgtm_strong:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/78#-:-LAslubj1HcBpDuA0ImI:b-jbsf8z)*

**Comment by dsmilkov** [comment]
Thanks! Couple comments.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[package.json, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/78#-LAsxYuf0N0SnzBz5_eZ:-LAsxYuf0N0SnzBz5_e_:b-rw2p7s) ([raw file](https://github.com/tensorflow/tfjs-node/blob/092aaffdd44b564c4af77f9a2eb0bfd5c8cc2bd5/package.json#L2)):*
> ```JSON
> {
>   "name": "@tensorflow/tfjs-node",
> ```

can you update the README.md where it says `yarn link-local tfjs-node` to `yarn link-local @tensorflow/tfjs-node`

---

*[demo/package.json, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/78#-LAsxNtdANakmHSOSRUY:-LAsxNteC4edaXeEJgrD:b-x421l6) ([raw file](https://github.com/tensorflow/tfjs-node/blob/092aaffdd44b564c4af77f9a2eb0bfd5c8cc2bd5/demo/package.json#L22)):*
> ```JSON
>   "dependencies": {
>     "@tensorflow/tfjs-core": "0.8.1",
>     "tfjs-node": "link:.yalc/@tensorflow/tfjs-node"
> ```

"@tensorflow/tfjs-node": "link:.yalc......

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/78#-:-LAsxdBC07Y2GG0o6RFs:b9netdz)*

**Comment by ry** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[package.json, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/78#-LAsxYuf0N0SnzBz5_eZ:-LAszIFkAVgmcDtg1fxY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-node/blob/092aaffdd44b564c4af77f9a2eb0bfd5c8cc2bd5/package.json#L2)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

can you update the README.md where it says `yarn link-local tfjs-node` to `yarn link-local @tensorflow/tfjs-node`
</blockquote></details>

Done.

---

*[demo/package.json, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs-node/78#-LAsxNtdANakmHSOSRUY:-LAszJdY0ey6CcLP3lAN:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-node/blob/092aaffdd44b564c4af77f9a2eb0bfd5c8cc2bd5/demo/package.json#L22)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

"@tensorflow/tfjs-node": "link:.yalc......
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/78)*

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/78#-:-LAt9haIDAeJzoEqDoNI:b-jbsf8z)*

**Pull request merged**
