### PR TITLE
file_system: group promisify, avoid relying on in-advance fs.exists checks

### PR DESCRIPTION
**Pull request by ChALkeR**
Again several commits here with their own descriptions.

This removes `fs.exists` usage and does some minor cleanup.
My intention was to remove the in-advance checks that might result in a race.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/112)

### CODE REVIEW

**Comment by ChALkeR** [comment]
Travis failure looks unrelated.

**Comment by ChALkeR** [comment]
@nkreeger Updated. That added one line though ;-).

**Comment by ChALkeR** [comment]
Ah, also, it was `Path ${path} does not exist: loading failed.`, but `Weight file ${path} does not exist: loading failed`, note the dot.

This PR changes that to a common variant (without the dot). Tests are happy both ways.
I can re-add it back if you want  :-). To both variants, that is.

**Comment by nkreeger** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/io/file_system.ts, line 121 at r2](https://reviewable.io/reviews/tensorflow/tfjs-node/112#-LGS20OyB6NIXHDW0KjS:-LGS20OyB6NIXHDW0KjT:bd97wh3) ([raw file](https://github.com/tensorflow/tfjs-node/blob/73fa4e3dc38ded3d2f2ca4ac317b539b72fde5d2/src/io/file_system.ts#L121)):*
> ```
> Path
> ```

I can see this getting confusing on the command line - do we need a name? If so, maybe something like 'Path from load' or 'loading model'. 

---

*[src/io/file_system.ts, line 139 at r2](https://reviewable.io/reviews/tensorflow/tfjs-node/112#-LGS2FJs5oZiz1f7ccK1:-LGS2FJs5oZiz1f7ccK2:b4x8f5p) ([raw file](https://github.com/tensorflow/tfjs-node/blob/73fa4e3dc38ded3d2f2ca4ac317b539b72fde5d2/src/io/file_system.ts#L139)):*
> ```
> 'Weight file'
> ```

Ditto here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/112)*

**Pull request merged**
