### PR TITLE
[WIP; Don't review yet] Add benchmark scripts for tfjs-node

### PR DESCRIPTION
**Pull request by caisq**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/221)

### CODE REVIEW

**Comment by annxingyuan** [comment]
@caisq Hey Shanqing - I just wanted to let you know about this PR: https://github.com/tensorflow/tfjs/issues/986

Also: https://github.com/tensorflow/tfjs-core/pull/1602

The idea is to move benchmarks out of individual packages and into union. Maybe the node benchmarks could follow the same pattern?

**Comment by caisq** [comment]
@annxingyuan For browser-based benchmarks I agree they should go to the same location. For node-based benchmarks, let's discuss. The union repo doesn't depend on tfjs-node. It's in fact the reverse. So doing benchmark from the union will be a little unwieldy. The union and tfjs-node are not on the same release cadence either, leading to further obstacles when developers make changes to one repo and hope to see the effect in the other.

**Comment by caisq** [comment]
@nkreeger @annxingyuan @dsmilkov this PR is just for my own prototyping. Please don't review or read too much into it. I'll write a detailed design before checking in any big chunks of code for this.

**Comment by annxingyuan** [comment]
@caisq Sounds good :)

**Pull request closed without merging**
