### PR TITLE
Add arm cpu check for  arm64  (AArch64) bindings

### PR DESCRIPTION
**Pull request by hossein-b**
look like there is no support for arm64  (AArch64) in tfjs-node. here is my try to install which I got the following error:

	ngd@localhost:~/tf/posenet$ sudo yarn add @tensorflow/tfjs-node
	yarn add v1.16.0
	info No lockfile found.
	[1/4] Resolving packages...
	[2/4] Fetching packages...
	[3/4] Linking dependencies...
	warning "@tensorflow/tfjs-node > @tensorflow/tfjs > @tensorflow/tfjs-data@1.2.1" has unmet peer dependency "seedrandom@~2.4.3".
	warning "@tensorflow/tfjs-node > @tensorflow/tfjs > @tensorflow/tfjs-core > rollup-plugin-visualizer@1.1.1" has unmet peer dependency "rollup@>=0.60.0".
	[4/4] Building fresh packages...
	error /home/ngd/tf/posenet/node_modules/@tensorflow/tfjs-node: Command failed.
	Exit code: 1
	Command: node scripts/install.js
	Arguments: 
	Directory: /home/ngd/tf/posenet/node_modules/@tensorflow/tfjs-node
	Output:
	* Downloading libtensorflow

	* Building TensorFlow Node.js bindings
	/home/ngd/tf/posenet/node_modules/@tensorflow/tfjs-node/scripts/install.js:165
		  throw new Error('node-gyp rebuild failed with: ' + err);
		  ^

	Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
	gyp info it worked if it ends with ok
	gyp info using node-gyp@3.8.0
	gyp info using node@10.16.0 | linux | arm64
	gyp info spawn /usr/bin/python2
	gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
	gyp info spawn args   'binding.gyp',
	gyp info spawn args   '-f',
	gyp info spawn args   'make',
	gyp info spawn args   '-I',
	gyp info spawn args   '/home/ngd/tf/posenet/node_modules/@tensorflow/tfjs-node/build/config.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/home/ngd/.node-gyp/10.16.0/include/node/common.gypi',
	gyp info spawn args   '-Dlibrary=shared_library',
	gyp info spawn args   '-Dvisibility=default',
	gyp info spawn args   '-Dnode_root_dir=/home/ngd/.node-gyp/10.16.0',
	gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
	gyp info spawn args   '-Dnode_lib_file=/home/ngd/.node-gyp/10.16.0/<(target_arch)/node.lib',
	gyp info spawn args   '-Dmodule_root_dir=/home/ngd/tf/posenet/node_modules/@tensorflow/tfjs-node',
	gyp info spawn args   '-Dnode_engine=v8',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '--no-parallel',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp info spawn make
	gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
	/usr/bin/ld: skipping incompatible ./Release/libtensorflow.so when searching for -ltensorflow
	/usr/bin/ld: cannot find -ltensorflow
	/usr/bin/ld: skipping incompatible ./Release/libtensorflow_framework.so when searching for -ltensorflow_framework
	/usr/bin/ld: cannot find -ltensorflow_framework
	collect2: error: ld returned 1 exit status
	make: *** [Release/obj.target/tfjs_binding.node] Error 1
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
	gyp ERR! System Linux 4.9.0-xilinx-v2017.3
	gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /home/ngd/tf/posenet/node_modules/@tensorflow/tfjs-node
	gyp ERR! node -v v10.16.0
	gyp ERR! node-gyp -v v3.8.0
	gyp ERR! not ok 

		at cp.exec (/home/ngd/tf/posenet/node_modules/@tensorflow/tfjs-node/scripts/install.js:165:13)
		at ChildProcess.exithandler (child_process.js:301:5)
		at ChildProcess.emit (events.js:198:13)
		at maybeClose (internal/child_process.js:982:16)
		at Socket.stream.socket.on (internal/child_process.js:389:11)
		at Socket.emit (events.js:198:13)
		at Pipe._handle.close (net.js:606:12)
	info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

could you please let me know anything wrong with my system that it doesn't work?

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-node/267)

### CODE REVIEW

**Comment by hossein-b** [comment]
I signed it!

**Comment by nkreeger** [comment]
Hi - I'm still looking to see if we have official libtensorflow arm64 binaries available. I'll circle back once I find more out..

In the mean time - I can't tell what your PR is doing. Do you mind resolving conflicts and updating? Thanks!

**Comment by hossein-b** [comment]
I build libtensorflow arm64 binaries by the following command:
`bazel build --config=monolithic --config=opt --config=noaws //tensorflow/tools/lib_package:libtensorflow`
and these confuguration,
`TF-Version = tensorflow-1.13.1`
`Python version = 2.7, 3.3-3.7`
`Compiler = GCC 9.1`
`Build tools = Bazel 0.19.2`
`java = openjdk-8-jdk`
The out output is "libtensorflow.so" and its include files.
the problem is I don't know what I have to do with these files. I think we need a page like this:
`https://malmaud.github.io/TensorFlow.jl/latest/build_from_source.html`
to explain step by step how to build TensorFlow from source for tfjs-node, I fund the following link but isn't enough:
`https://github.com/tensorflow/tfjs-node#optional-build-libtensorflow-from-tensorflow-source`  
The second problem is, when using `yarn` command, it automatically downloads libtensorflow for amd64 as this is the only availed version for Ubuntu. Look like `yarn` command is not able to realize architecture. 
I just copy the libtensorflow.so to node_modules/@tensorflow/tfjs-node/deps/lib/libtensorflow.so inside the project.
I tried to use these commands to build tfjs-node:
`npm i -g nan`
`export NODE_PATH=$(npm root -g)`
`node-gyp configure`
`node-gyp build`
But it wasn't successful. Am I in the right way?

**Comment by nkreeger** [comment]
We'll be pushing out arm64 builds once they are officially supported in core TensorFlow.

**Pull request closed without merging**
